# Generated by Django 4.2.2 on 2023-06-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seattle_emcalc", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MonModele",
        ),
    ]
