# Generated by Django 4.2.2 on 2023-06-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("seattle_emcalc", "0002_delete_monmodele"),
    ]

    operations = [
        migrations.CreateModel(
            name="buildings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "buildings",
            },
        ),
    ]
