# Generated by Django 4.2.2 on 2023-06-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("seattle_emcalc", "0004_delete_buildings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buildings",
            fields=[
                ("osebuildingid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "buildingtype",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "primarypropertytype",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "propertyname",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "taxparcelidentificationnumber",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("councildistrictcode", models.IntegerField(blank=True, null=True)),
                (
                    "neighborhood",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("yearbuilt", models.IntegerField(blank=True, null=True)),
                ("numberofbuildings", models.IntegerField(blank=True, null=True)),
                ("numberoffloors", models.IntegerField(blank=True, null=True)),
                ("propertygfatotal", models.FloatField(blank=True, null=True)),
                ("propertygfaparking", models.FloatField(blank=True, null=True)),
                ("propertygfabuilding_s", models.FloatField(blank=True, null=True)),
                (
                    "listofallpropertyusetypes",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "largestpropertyusetype",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("largestpropertyusetypegfa", models.FloatField(blank=True, null=True)),
                ("energystarscore", models.FloatField(blank=True, null=True)),
                ("siteeui_kbtu_sf", models.FloatField(blank=True, null=True)),
                ("siteeuiwn_kbtu_sf", models.FloatField(blank=True, null=True)),
                ("sourceeui_kbtu_sf", models.FloatField(blank=True, null=True)),
                ("sourceeuiwn_kbtu_sf", models.FloatField(blank=True, null=True)),
                ("siteenergyuse_kbtu", models.FloatField(blank=True, null=True)),
                ("siteenergyusewn_kbtu", models.FloatField(blank=True, null=True)),
                ("steamuse_kbtu", models.FloatField(blank=True, null=True)),
                ("electricity_kwh", models.FloatField(blank=True, null=True)),
                ("electricity_kbtu", models.FloatField(blank=True, null=True)),
                ("naturalgas_therms", models.FloatField(blank=True, null=True)),
                ("naturalgas_kbtu", models.FloatField(blank=True, null=True)),
                ("totalghgemissions", models.FloatField(blank=True, null=True)),
                ("ghgemissionsintensity", models.FloatField(blank=True, null=True)),
                (
                    "secondlargestpropertyusetype",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "secondlargestpropertyusetypegfa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "thirdlargestpropertyusetype",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "thirdlargestpropertyusetypegfa",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "yearsenergystarcertified",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "buildings",
                "managed": False,
            },
        ),
    ]
