# Generated by Django 4.2.2 on 2023-06-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seattle_emcalc", "0005_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primarypropertytype",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("yearbuilt", models.IntegerField(blank=True, null=True)),
                ("numberofbuildings", models.IntegerField(blank=True, null=True)),
                ("numberoffloors", models.IntegerField(blank=True, null=True)),
                ("propertygfatotal", models.FloatField(blank=True, null=True)),
                ("propertygfaparking", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "new_building",
            },
        ),
    ]
