# Generated by Django 4.2.2 on 2023-06-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seattle_emcalc", "0006_newbuilding"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newbuilding",
            options={"managed": False},
        ),
    ]
