# Generated by Django 4.2.2 on 2023-06-30 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seattle_emcalc", "0008_uploadfile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadFile",
        ),
    ]
